Catchv3 support in tests.
MRChemSoft/mrcpp pull request #213
Opened 2023-08-09 21:28 UTC by susilehtola

Closes #211 

This code follows the recent Catch v3 port in https://github.com/wavefunction91/IntegratorXX/

2023-08-17 06:24 UTC, robertodr commented on cmake/DownloadProject.cmake
Is this file necessary? `FetchContent` is part of CMake nowadays, indeed we do use it already extensively in MRCPP/MRChem.

2023-08-17 06:26 UTC, robertodr commented on tests/CMakeLists.txt
Can you rewrite the bit of the CMake script where you fetch to something like this? `MakeAvailable` will populate and add the subdirectory.

https://github.com/MRChemSoft/mrcpp/blob/df9b05402e8d2c88ecda066ef728f3088d57d3e5/external/upstream/fetch_eigen3.cmake

2023-08-17 06:27 UTC, robertodr requested changes
Thanks! I'd been wanting to do this for a long time :) Please see my comments on what should be changed.

2023-08-17 18:05 UTC, susilehtola commented on tests/CMakeLists.txt
Done

2023-08-17 18:05 UTC, susilehtola commented on cmake/DownloadProject.cmake
Removed

2023-08-18 09:20 UTC, robertodr approved these changes
Thank you!

2023-08-18 09:21 UTC, merged