Save or read orbitals in text format, portable and readable by MADNESS group
MRChemSoft/mrcpp pull request #249
Opened 2024-12-30 10:32 UTC by gitpeterwind

Orbitals can be saved and read in text format (ascii) files. Each end node is saved with info about depth and translation.
Use keyword write_orbitals_txt = T to save in this format.

Also introduced keywords  `bank_per_node` and `use_omp_num_threads` after feedback from Moritz and Roberto. (see documentation)

NB: this PR builds on top of the Four Components PR and is to be used with the corresponding MRChem PR.

2025-01-18 11:50 UTC, robertodr commented on src/functions/RepresentableFunction.h
> +template <int D, typename T> class RepresentableFunction {
Why not have a default for `T` here?
```suggestion
template <int D, typename T = double> class RepresentableFunction {
```

2025-01-18 11:59 UTC, robertodr commented on src/functions/RepresentableFunction.cpp
> +template class RepresentableFunction<1, double>;
here we might want to instantiate also for `float` and `std::complex<float>`. Maybe we should have a macro to do it for us, because we'd then be at 12 lines of boilerplate for almost every class. I might have something in my archives...

2025-01-18 12:02 UTC, robertodr commented on src/operators/OperatorState.h
> +template <int D, typename T> class OperatorState final {
also here we can have a default for T, as the class is marked as `final` and we can't inherit from it anyway
```suggestion
template <int D, typename T = double> class OperatorState final {
```

2025-01-18 12:04 UTC, robertodr commented on src/operators/OperatorStatistics.h
> +    void incrementFNodeCounters(const MWNode<D, T> &fNode, int ft, int gt);
Actually, I don't think this class should be templated on both `D` and `T` at all. It might be enough to simply template the methods that accept a `MWNode` object :thinking:

2025-01-18 12:06 UTC, robertodr commented on src/treebuilders/AdditionCalculator.h
> +    void calcNode(MWNode<D, double> &node_o) {
I believe we can keep the `override` marker here. We don't need to have two implementations for the different scalar types: one can use `if constexpr` to do compile-time, type-level checks nowadays. Of course it's going to be a bit of an ugly function...

2025-01-18 12:31 UTC, robertodr commented on src/treebuilders/CrossCorrelationCalculator.cpp
>          VectorXd vec_b;
```suggestion
        VectorXd vec_a, vec_b;
```

2025-01-18 12:34 UTC, robertodr commented on src/treebuilders/DerivativeCalculator.cpp
> +    /*
Should the commented-out code be removed altogether? Eigen does have the possibility of offloading to BLAS/LAPACK https://eigen.tuxfamily.org/dox/TopicUsingBlasLapack.html

2025-01-18 13:50 UTC, robertodr commented on src/treebuilders/MultiplicationCalculator.h
> +    void calcNode(MWNode<D, double> &node_o) {
Same comment as for the other calculator.

2025-01-18 13:51 UTC, robertodr commented on src/treebuilders/SquareCalculator.h
> +    void calcNode(MWNode<D, double> &node_o) {
Same comment here as well

2025-01-18 13:53 UTC, robertodr commented on src/treebuilders/add.cpp
> +template void add<1, double>(double prec,
yes, a macro would go a very long way to reduce the boilerplate also for these instantiations!

2025-01-18 13:59 UTC, robertodr commented on src/treebuilders/apply.cpp
> +    if (metric == nullptr) {
C++17 introduced [`std::optional`](https://en.cppreference.com/w/cpp/utility/optional) to deal with arguments that may or may not be passed. We should use that here.

2025-01-18 14:00 UTC, robertodr commented on src/treebuilders/apply.cpp
> +    if (metric == nullptr) {
Same comment about `std::optional` applies also here.

2025-01-18 14:01 UTC, robertodr commented on src/treebuilders/apply.cpp
> +    if (metric == nullptr) {
`std::optional` also here.

2025-01-18 14:01 UTC, robertodr commented on src/treebuilders/apply.cpp
> +    //TODO: sums and not only each components independently
TODO still relevant?

2025-01-18 14:01 UTC, robertodr commented on src/treebuilders/apply.cpp
> +                        else out.func_ptr->data.c1[ocomp] *= metric[icomp][ocomp]; //TODO: multiply c1 in rescale?
TODO still relevant?

2025-01-18 14:09 UTC, robertodr commented on src/treebuilders/map.cpp
> +void map(double prec, FunctionTree<D, double> &out, FunctionTree<D, double> &inp, FMap<double, double> fmap, int maxIter, bool absPrec) {
is `map` not relevant when one has `float` or `std::complex` scalar types?

2025-01-18 14:16 UTC, robertodr commented on src/treebuilders/multiply.h
> +                            FunctionTree<D, ComplexDouble> &ket);
I think it's enough to have one function, but with three template parameters (similarly could be done for all arithmetic functions, actually)
```suggestion
template <int D, typename T, typename U = T, typename V = decltype(std::declval<T>() * std::declval<U>())>
V dot(FunctionTree<D, T> &bra, FunctionTree<D, U> &ket);
```
you can see why I dislike implementing templates in `.cpp` files :sweat_smile: (cough cough @ilfreddy)

Note that in the C++ standard mixing `float` and `std::complex<double>` (or `double` and `std::complex<float>`) is _not_ possible, so the above should be combined with a compile-time exclusion of such a possibility (through SFINAE or something) Another thing I have in my archives.

2025-01-18 14:19 UTC, robertodr commented on src/trees/FunctionNode.h
> +template <int D>
again, I think these signatures can be declared only once using the "trick" above.

2025-01-18 14:22 UTC, robertodr commented on src/trees/FunctionTree.cpp
> + */
The docstring here seems a bit mangled. Can you fix it?

2025-01-18 14:24 UTC, robertodr commented on src/trees/FunctionTree.cpp
> +        if (std::abs(coord[d][1] - L) > TXT_thres) NOT_IMPLEMENTED_ABORT;
I don't understand why the 2nd and 4th statements

2025-01-18 14:27 UTC, robertodr commented on src/trees/FunctionTree.cpp
> +                                      MWTree<D, double> &refTree,
here (and some other places) you explicitly fix the scalar type of some function inputs. Why is that?

2025-01-18 14:30 UTC, robertodr commented on src/trees/FunctionTree.cpp
> +    /*
I think it's fine to delete commented-out code.

2025-01-18 14:35 UTC, robertodr commented on src/trees/MWNode.cpp
> +//#ifdef HAVE_BLAS
commented-out code can be removed

2025-01-18 14:38 UTC, robertodr commented on src/trees/MultiResolutionAnalysis.cpp
> +    if (this->basis != mra.basis) std::cout<<"diff basis "<<this->basis<<std::endl <<"and  "<< mra.basis<<std::endl;
are the print statements needed here? if yes, maybe the should use the printer. Also, no need to check the condition twice, just do a non-inline if-statement.

2025-01-18 14:49 UTC, robertodr requested changes
* Can you run `clang-format` on all the C++ files this PR changes?
* When giving a default for the scalar type (_e.g._ `typename T = double`) I think it should be enough to do it on the parent classes. This is however just to save some typing :)
* I think we should have compile-time checks on whether the scalar type `T` makes sense or not, _e.g._ only one of `float`, `double`, `std::complex<float>`, `std::complex<double>`. I have some code to do this that we can reuse.
* For the `metric` arguments of some functions in `apply` we may use `std::optional<Eigen::Matrix<std::complex<double>, 4, 4>>`.
* There's a lot more boilerplate in the explicit instantiations. The obvious solution is to _not_ put the implementation in `.cpp` files, but leave everything in the header. @ilfreddy (and maybe @stigrj?) feels strongly against it, so we'll have to make do with some preprocessor macros and/or some metaprogramming tricks.
* I think we should allow to mix scalar types, but it can be left for a future refinement, as it involves some tricky gymnastics with template parameters.

2025-01-18 14:51 UTC, robertodr commented on src/utils/math_utils.h
> +void apply_filter(ComplexDouble *out, ComplexDouble *in, const Eigen::MatrixXd &filter, int kp1, int kp1_dm1, double fac);
I think the two can be unified with `if constexpr`

2025-01-18 14:54 UTC, robertodr reviewed
* in `parallel.h`/`parallel.cpp` I think the implementations for `double` and `std::complex<double>` could be unified, so we reduce a bit the boilerplate (and possibly extend to `float`)

2025-01-27 11:16 UTC, gitpeterwind commented on src/functions/RepresentableFunction.h
> +template <int D, typename T> class RepresentableFunction {
it is already set as default in mrcpp_declarations.h

2025-01-27 12:04 UTC, gitpeterwind commented on src/operators/OperatorState.h
> +template <int D, typename T> class OperatorState final {
it is already set as default in mrcpp_declarations.h

2025-01-27 13:23 UTC, gitpeterwind commented on src/treebuilders/apply.cpp
> +                        else out.func_ptr->data.c1[ocomp] *= metric[icomp][ocomp]; //TODO: multiply c1 in rescale?
I rephrased: // To consider: multiply c1 in rescale?
 The "c1 constant" is somewhat new and it is not yet completely integrated into the logic. It is a "soft" multiplicative constant; soft meaning the same as the conjugate flag for a function: not explicitly applied before it is required. 
 So far it is used for the complex spin operators: we do not want to convert all real functions to complex just because there is a complex multiplicative factor in the operator.

2025-01-27 13:27 UTC, gitpeterwind commented on src/treebuilders/map.cpp
> +void map(double prec, FunctionTree<D, double> &out, FunctionTree<D, double> &inp, FMap<double, double> fmap, int maxIter, bool absPrec) {
I don't know, but since it is not used I prefer to not implement before we know what we want to use it for.

2025-01-27 14:39 UTC, gitpeterwind commented on src/treebuilders/multiply.h
> +                            FunctionTree<D, ComplexDouble> &ket);
This is nice!

2025-01-27 14:39 UTC, gitpeterwind commented on src/trees/FunctionNode.h
> +template <int D>
I did not use the trick for the dot_scaling and dot_wavelet, because with the conjugate flags it became messy.

2025-01-28 11:04 UTC, gitpeterwind commented
I have now included all the changes you proposed, or left a comment.
It is a pity that I did not use the `if constexpr` from the start. Actually I did, but then went back because it was not compliant with the std14. 
About using float I am sceptical: for small system there is no point, and for large "HPC" systems the error would be too large. Roughly a HPC calculation would take 10¹² operation at least, giving sqrt(10⁻¹²)  = 10⁻⁶ relative numerical error, 6 digits error of about 7 significant digits is not useful.
About reducing the boilerplate instantiations, I do not think it is important: it is not those parts that take time to implement, and they do not reduce code readability (while macros might!).

2025-01-28 12:59 UTC, gitpeterwind commented
yes

2025-02-18 13:26 UTC, merged